// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGCt9uE-Ega664KxrQH3Lh9yQOGlhIUk',
    appId: '1:187311862034:web:0ce8c62ee2489c275b43cb',
    messagingSenderId: '187311862034',
    projectId: 'klick-wash-f903c',
    authDomain: 'klick-wash-f903c.firebaseapp.com',
    storageBucket: 'klick-wash-f903c.appspot.com',
    measurementId: 'G-6X3R1KBMG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5M8WjpcdNu6mmYZDeWIW5iLxJk3TaHjw',
    appId: '1:187311862034:android:673ab0395873a3165b43cb',
    messagingSenderId: '187311862034',
    projectId: 'klick-wash-f903c',
    storageBucket: 'klick-wash-f903c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADr-ZCowxbtHm5hcvCks4BqyfsdGOTXJ4',
    appId: '1:187311862034:ios:20d0575eda73f0375b43cb',
    messagingSenderId: '187311862034',
    projectId: 'klick-wash-f903c',
    storageBucket: 'klick-wash-f903c.appspot.com',
    iosClientId: '187311862034-n211iv87oglqubnocibhaeuh619iq9a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.klicksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADr-ZCowxbtHm5hcvCks4BqyfsdGOTXJ4',
    appId: '1:187311862034:ios:20d0575eda73f0375b43cb',
    messagingSenderId: '187311862034',
    projectId: 'klick-wash-f903c',
    storageBucket: 'klick-wash-f903c.appspot.com',
    iosClientId: '187311862034-n211iv87oglqubnocibhaeuh619iq9a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.klicksApp',
  );
}
